### PR TITLE
Move source into start command

### PR DESCRIPTION
**Pull request by nmuesch**
### What does this PR do?

Move the source of the scripts that ensure the agent has the proper permissions on directories, inside the beginning of the start command. This ensures we don't execute commands like chown/chmod on directories when the agent is trying to stop. This also adds a log line prior to starting so we can see how long this step takes.

### Verification Process

Tested by building a custom release and deploying on the lab. Then confirmed the processes were all started by `monit status`. I then manually stopped the datadog-agent service via monit to ensure it could stop properly. 

### Review checklist (to be filled by reviewers)

- [ ] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Comment by zippolyte** [comment]
Can we also add a log line near the beginning of this entire file (like right after we declare the `echo_log` function, just to be safe ?

**Comment by nmuesch** [comment]
Thanks, we define echon_log in lib.sh, which is only one source above the bottom, so I didn't wind up adding more logging.

**Comment by zippolyte** [comment]
Oh can we do that for other ctl scripts as well, like process, and so on ?

**Comment by nmuesch** [comment]
@zippolyte It looks like system_probe is the only other ctl we do ensure_directories for, but I also moved the source there, thanks!

**Review by zippolyte — APPROVED** [review]

**Pull request merged**
