### PR TITLE
Add apm_enabled to Agent config template

### PR DESCRIPTION
**Pull request by kmshultz**
@gmmeyer do you think we should add this?

### CODE REVIEW

**Comment by gmmeyer** [comment]
We can, but I think it's useless. Almost no one will use it. APM will be primarily used in a service broker. Unless you can think of a use case for it here?

**Comment by gmmeyer** [comment]
Also, this won't be enough, you'd have to add a new monit template for the apm agent.

**Comment by kmshultz** [comment]
Yes, I didn't add the monit bit yet because I wasn't sure we wanted to add this at all. We can abandon it.

**Comment by gmmeyer** [comment]
@kmshultz I think we should do it for completeness, and in case anyone wants to use it.

**Comment by gmmeyer** [comment]
You just add this to datadog.conf to chnage the port:

```
[trace.receiver]
# the port that the Receiver should listen on
receiver_port: 8126
```

**Pull request closed without merging**
